[versions]
agp = "8.5.1"              # Compatible with compileSdk 34
kotlin = "1.9.0"
coreKtx = "1.12.0"         # Last stable version compatible with SDK 34
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.6.2"  # Compatible with SDK 34
activityCompose = "1.8.2"      # Compatible with SDK 34
composeBom = "2024.02.00"
adsMobileSdk = "0.21.0-beta01"

zxing = "4.3.0"
zxing-core = "3.5.2"
qrgen = "3.0.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "2.6.2" }
ads-mobile-sdk = { group = "com.google.android.libraries.ads.mobile.sdk", name = "ads-mobile-sdk", version.ref = "adsMobileSdk" }
googlecode-libphonenumber = { group = "com.googlecode.libphonenumber", name = "libphonenumber", version = "8.13.45" }
firebasebom = { group = "com.google.firebase", name = "firebase-bom", version = "32.2.2" }
firebaseauth = { group = "com.google.firebase", name = "firebase-auth-ktx" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version = "1.1.1" }
camera-core = { group = "androidx.camera", name = "camera-core", version = "1.3.4" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version = "1.3.4" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version = "1.3.4" }
camera-view = { group = "androidx.camera", name = "camera-view", version = "1.3.4" }
zxing-embedded = { group = "com.journeyapps", name = "zxing-android-embedded", version.ref = "zxing" }
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing-core" }
qrgen-android = { group = "com.github.kenglxn.QRGen", name = "android", version.ref = "qrgen" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging-ktx" }
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version = "2.6.2" }
retrofit2-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version = "2.6.0" }




[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version = "4.4.1" }
